apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/soyjoy666666/uti-study:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/soyjoy666666/uti-study:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: uti-study
        chartPath: charts/uti-study
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/soyjoy666666/uti-study'
          image.tag: '{{.DIGEST_HEX}}'
